name: Python Greetings

on:
  push:
    branches: ["main"]
    
  workflow_dispatch:

jobs:
  install-pip-dev:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'mtararujs/python-greetings'
          path: 'api-tests'
      - name: install
        run: echo instalē pip dependencies...
      - name: install-pip-deps
        working-directory: api-tests
        run: pip install -r requirements.txt
  dep-to-dev:
    runs-on: self-hosted
    needs: [install-pip-dev]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'mtararujs/python-greetings'
          path: 'api-tests'
      - name: deploy-to-dev
        run: echo delpoying to development...
      - name: pm2-start
        working-directory: api-tests
        run:   pm2 start app.py --name greetings-app-greetings-app-dep-to-dev -- --port 7001
      - name: pm2-del
        working-directory: api-tests
        run:  pm2 delete greetings-app-dep-to-dev & set "errorlevel=0"
  test-on-dev:
    runs-on: self-hosted
    needs: [dep-to-dev]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'mtararujs/course-js-api-framework'
          path: 'js-api-framework'
      - name: deploy-to-dev
        run: echo testing to development...
      - name: npm-install
        working-directory: js-api-framework
        run:   npm install
      - name: npm-run
        working-directory: api-tests
        run:  npm run greetings greetings_on_dev
  dep-to-stag:
    runs-on: self-hosted
    needs: [test-on-dev]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'mtararujs/python-greetings'
          path: 'api-tests'
      - name: deploy-to-stag
        run: echo delpoying to staging...
      - name: pm2-start
        working-directory: api-tests
        run:   pm2 start app.py --name greetings-app-dep-to-stag -- --port 7002
      - name: pm2-del
        working-directory: api-tests
        run:  pm2 delete greetings-app-dep-to-stag & set "errorlevel=0"
  test-on-stag:
    runs-on: self-hosted
    needs: [dep-to-stag]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'mtararujs/course-js-api-framework'
          path: 'js-api-framework'
      - name: deploy-to-dev
        run: echo testing to staging...
      - name: npm-install
        working-directory: js-api-framework
        run:   npm install
      - name: npm-run
        working-directory: api-tests
        run:  npm run greetings greetings_on_staging
  dep-to-preprod:
    runs-on: self-hosted
    needs: [test-on-stag]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'mtararujs/python-greetings'
          path: 'api-tests'
      - name: deploy-to-preprod
        run: echo delpoying to preproduction...
      - name: pm2-start
        working-directory: api-tests
        run:   pm2 start app.py --name greetings-app-dep-to-preprod -- --port 7003
      - name: pm2-del
        working-directory: api-tests
        run:  pm2 delete greetings-app-dep-to-preprod & set "errorlevel=0"
  test-on-preprod:
    runs-on: self-hosted
    needs: [dep-to-preprod]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'mtararujs/course-js-api-framework'
          path: 'js-api-framework'
      - name: deploy-to-dev
        run: echo testing on preprod...
      - name: npm-install
        working-directory: js-api-framework
        run:   npm install
      - name: npm-run
        working-directory: api-tests
        run:  npm run greetings greetings_on_preproduction
  dep-to-prod:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'mtararujs/python-greetings'
          path: 'api-tests'
      - name: deploy-to-prod
        run: echo delpoying to production...
      - name: pm2-start
        working-directory: api-tests
        run:   pm2 start app.py --name greetings-app-dep-to-prod -- --port 7004
      - name: pm2-del
        working-directory: api-tests
        run:  pm2 delete greetings-app-dep-to-prod & set "errorlevel=0"
  test-on-prod:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'mtararujs/course-js-api-framework'
          path: 'js-api-framework'
      - name: deploy-to-dev
        run: echo testing on prod...
      - name: npm-install
        working-directory: js-api-framework
        run:   npm install
      - name: npm-run
        working-directory: api-tests
        run:  npm run greetings greetings_on_prod
